version: '3.8'

services:
  pg-keycloak:
    image: postgres:15
    container_name: pg-keycloak
    restart: always
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpass
      POSTGRES_DB: kcdb
    ports:
      - "5433:5432"
    volumes:
      - pgkcdata:/var/lib/postgresql/data

  pg-app:
    image: postgres:15
    container_name: pg-app
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgappdata:/var/lib/postgresql/data
  
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpass
      KC_DB: postgres
      KC_DB_URL_HOST: pg-keycloak
      KC_DB_URL_DATABASE: kcdb
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpass
    ports:
      - "8080:8080"
    depends_on:
      - pg-keycloak

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  pgkcdata:
  pgappdata:
